In [23]:
from may2025_report_exhibits import sctevt_df
import pandas as pd
from sams.analysis.utils import save_table_excel

In [24]:
# Set year to 2022
sctevt_df_2022 = sctevt_df[sctevt_df["year"] == 2022]
sctevt_df_2022 = sctevt_df_2022[sctevt_df_2022["gender"] != "O"]
sctevt_dropouts_df_2022 = sctevt_df_2022[sctevt_df_2022["dropout"]]

In [29]:
sctevt_df.columns

Index(['year', 'roll_num', 'iti_code', 'trade', 'gender', 'overall_result_y1',
       'overall_result_y2', 'type_of_institute', 'course_period', 'dropout',
       'retained'],
      dtype='object')

In [25]:
# SCTEVT enrollment in 2022 by trade and gender
sctevt_enrollment_trades_gender_2022 = pd.pivot_table(
    sctevt_df_2022,
    index='trade',
    columns='gender',
    values='roll_num',
    aggfunc='nunique'
)

sctevt_enrollment_trades_gender_2022 = sctevt_enrollment_trades_gender_2022.astype("Int64")
sctevt_enrollment_trades_gender_2022["Total"] = sctevt_enrollment_trades_gender_2022.sum(axis=1)
sctevt_enrollment_trades_gender_2022 = sctevt_enrollment_trades_gender_2022.sort_values(by="Total", ascending=False)
sctevt_enrollment_trades_gender_2022

gender                                              Female   Male  Total
trade
Electrician (NSQF)                                    2027  19376  21403
Fitter (NSQF)                                         1392  17281  18673
Welder (NSQF)                                          317   2140   2457
Computer Operator and Programming Assistant (NSQF)     923    639   1562
Mechanic (Motor Vehicle) (NSQF)                         82   1131   1213
Electronics Mechanic (NSQF)                            211    747    958
Sewing Technology (NSQF)                               871     52    923
Mechanic Diesel (NSQF)                                  33    579    612
Machinist (NSQF)                                        56    521    577
Plumber (NSQF)                                          69    463    532
Wireman (NSQF)                                          45    434    479
REFRIGERATION AND AIR CONDITIONING TECHNICIAN(N...      89    382    471
Turner (NSQF)                                           42    382    424
Dress Making (NSQF)                                    339      8    347
Solar Technician (Electrical) (NSQF)                    75    241    316
Draughtsman (Civil) (NSQF)                             111    145    256
Information Communication Technology System Mai...      86    105    191
Instrument Mechanic (NSQF)                              24    138    162
Painter General (NSQF)                                  57     82    139
Draughtsman (Mechanical) (NSQF)                         30    104    134
Carpenter (NSQF)                                         7    125    132
Technician Mechatronics (NSQF)                          19     98    117
Pump Operator-Cum-Mechanic (NSQF)                        3     97    100
Smartphone Technician Cum App Tester (NSQF)             13     83     96
Mechanic Machine Tool Maintenance (NSQF)                 4     90     94
Computer Hardware & Network Maintenance (NSQF)          27     66     93
Mechanic Mining Machinery (NSQF)                         9     80     89
Electrician (DST) (NSQF)                                 1     86     87
Mechanic Auto Body Repair (NSQF)                         2     74     76
Surveyor (NSQF)                                         39     36     75
Industrial Painter (NSQF)                               29     43     72
Stenographer & Secretarial Assistant (English) ...      42     27     69
Stone Mining Machine Operator (NSQF)                    12     56     68
Stone Processing Machine Operator (NSQF)                15     52     67
Additive Manufacturing Technician Three D Print...      16     46     62
Mechanic (Tractor) (NSQF)                                5     55     60
Plastic Processing Operator (NSQF)                      15     45     60
Sheet Metal Worker (NSQF)                                5     54     59
Food Production (General) (NSQF)                        41      7     48
IoT Technician (Smart City)(NSQF)                       17     31     48
Attendant Operator (Chemical Plant) (NSQF)              12     36     48
Baker and Confectioner (NSQF)                           42      6     48
Tool & Die Maker (Press Tools, Jigs & Fixtures)...    <NA>     48     48
IoT Technician (Smart Agriculture)(NSQF)                21     27     48
Mechanic Agriculture Machinery (NSQF)                   10     38     48
IoT Technician (Smart healthcare)(NSQF)                 24     24     48
Health Sanitary Inspector (NSQF)                        29     12     41
Welder (GMAW & GTAW) (NSQF)                              9     31     40
Operator Advanced Machine Tools (NSQF)                   2     29     31
Computer Operator & Programming Assistant (VI) ...       8     16     24
Foundryman (NSQF)                                     <NA>     24     24
Textile Wet Processing Technician (NSQF)                20   <NA>     20
Laboratory Assistant (Chemical Plant) (NSQF)             8     12     20
Marine Engine Fitter (NSQF)                           <NA>     20     20
Laboratory Assistant-Chemical Plant (NSQF)               3     16     19
Mechanic Auto Body Painting (NSQF)                    <NA>     15     15
Secretarial Practice (English) (NSQF)                   10      1     11
Horticulture (NSQF)                                      7      1      8
Mason (Building Constructor) (NSQF)                   <NA>      2      2
Desk Top Publishing Operator (NSQF)                      1   <NA>      1

In [26]:
# SCTEVT dropouts by trade and gender in 2022
sctevt_dropouts_trades_gender_2022 = pd.pivot_table(
    sctevt_dropouts_df_2022,
    index='trade',
    columns='gender',
    values='roll_num',
    aggfunc='nunique'
)

sctevt_dropouts_trades_gender_2022 = sctevt_dropouts_trades_gender_2022.astype("Int64")
sctevt_dropouts_trades_gender_2022["Total"] = sctevt_dropouts_trades_gender_2022.sum(axis=1)

# Order dropouts by the order in the enrollment table
ordered_trades = sctevt_enrollment_trades_gender_2022.index
sctevt_dropouts_trades_gender_2022 = sctevt_dropouts_trades_gender_2022.reindex(ordered_trades)
sctevt_dropouts_trades_gender_2022

gender                                              Female  Male  Total
trade
Electrician (NSQF)                                     893  4253   5146
Fitter (NSQF)                                          817  5106   5923
Welder (NSQF)                                          134   437    571
Computer Operator and Programming Assistant (NSQF)     133   101    234
Mechanic (Motor Vehicle) (NSQF)                         32   358    390
Electronics Mechanic (NSQF)                             78   211    289
Sewing Technology (NSQF)                               312    37    349
Mechanic Diesel (NSQF)                                   4    84     88
Machinist (NSQF)                                        21   112    133
Plumber (NSQF)                                          39   125    164
Wireman (NSQF)                                          13   133    146
REFRIGERATION AND AIR CONDITIONING TECHNICIAN(N...    <NA>  <NA>   <NA>
Turner (NSQF)                                           15   111    126
Dress Making (NSQF)                                     59     3     62
Solar Technician (Electrical) (NSQF)                    13    64     77
Draughtsman (Civil) (NSQF)                              45    59    104
Information Communication Technology System Mai...      17    43     60
Instrument Mechanic (NSQF)                               3    39     42
Painter General (NSQF)                                  26    33     59
Draughtsman (Mechanical) (NSQF)                         18    53     71
Carpenter (NSQF)                                         6    28     34
Technician Mechatronics (NSQF)                           3    33     36
Pump Operator-Cum-Mechanic (NSQF)                        1    37     38
Smartphone Technician Cum App Tester (NSQF)           <NA>  <NA>   <NA>
Mechanic Machine Tool Maintenance (NSQF)                 2    29     31
Computer Hardware & Network Maintenance (NSQF)           1    13     14
Mechanic Mining Machinery (NSQF)                         1    18     19
Electrician (DST) (NSQF)                              <NA>  <NA>   <NA>
Mechanic Auto Body Repair (NSQF)                         2    12     14
Surveyor (NSQF)                                       <NA>  <NA>   <NA>
Industrial Painter (NSQF)                               12     8     20
Stenographer & Secretarial Assistant (English) ...      19    12     31
Stone Mining Machine Operator (NSQF)                  <NA>    10     10
Stone Processing Machine Operator (NSQF)                 1     4      5
Additive Manufacturing Technician Three D Print...       4     8     12
Mechanic (Tractor) (NSQF)                                5    15     20
Plastic Processing Operator (NSQF)                       6    13     19
Sheet Metal Worker (NSQF)                                1     8      9
Food Production (General) (NSQF)                        11     3     14
IoT Technician (Smart City)(NSQF)                     <NA>  <NA>   <NA>
Attendant Operator (Chemical Plant) (NSQF)               1     5      6
Baker and Confectioner (NSQF)                           14     1     15
Tool & Die Maker (Press Tools, Jigs & Fixtures)...    <NA>    21     21
IoT Technician (Smart Agriculture)(NSQF)              <NA>  <NA>   <NA>
Mechanic Agriculture Machinery (NSQF)                 <NA>     9      9
IoT Technician (Smart healthcare)(NSQF)               <NA>  <NA>   <NA>
Health Sanitary Inspector (NSQF)                         7     7     14
Welder (GMAW & GTAW) (NSQF)                              4     5      9
Operator Advanced Machine Tools (NSQF)                   2     9     11
Computer Operator & Programming Assistant (VI) ...    <NA>  <NA>   <NA>
Foundryman (NSQF)                                     <NA>     1      1
Textile Wet Processing Technician (NSQF)                 8  <NA>      8
Laboratory Assistant (Chemical Plant) (NSQF)          <NA>     2      2
Marine Engine Fitter (NSQF)                           <NA>     2      2
Laboratory Assistant-Chemical Plant (NSQF)            <NA>  <NA>   <NA>
Mechanic Auto Body Painting (NSQF)                    <NA>     4      4
Secretarial Practice (English) (NSQF)                 <NA>  <NA>   <NA>
Horticulture (NSQF)                                      3  <NA>      3
Mason (Building Constructor) (NSQF)                   <NA>  <NA>   <NA>
Desk Top Publishing Operator (NSQF)                   <NA>  <NA>   <NA>

In [27]:
# Compute enrollment by instiute in 2022
sctevt_enrollment_inst_2022 = pd.pivot_table(
    sctevt_df_2022,
    index='institute_name',
    values='roll_num',
    aggfunc='nunique'
)

sctevt_enrollment_inst_2022 = sctevt_enrollment_inst_2022.astype("Int64")

# Merge institute type column
sctevt_enrollment_inst_2022 = pd.merge(sctevt_enrollment_inst_2022, sctevt_df_2022[["institute_name", "type_of_institute"]].drop_duplicates(), on="institute_name", how="left")

sctevt_enrollment_inst_2022.rename(columns={"roll_num":"enrollment"}, inplace=True)
cols_order = ["institute_name", "type_of_institute", "enrollment"]
sctevt_enrollment_inst_2022 = sctevt_enrollment_inst_2022[cols_order]
sctevt_enrollment_inst_2022

KeyError: 'institute_name'

In [ ]:
# Compute dropout by institute in 2022
sctevt_dropouts_inst_2022 = pd.pivot_table(
    sctevt_dropouts_df_2022,
    index='institute_name',
    values='roll_num',
    aggfunc='nunique'
)

sctevt_dropouts_inst_2022 = sctevt_dropouts_inst_2022.astype("Int64")
sctevt_dropouts_inst_2022.rename(columns={"roll_num":"dropouts"}, inplace=True)
sctevt_dropouts_inst_2022

In [ ]:
# Merge enrollment and dropout table on institutes
sctevt_enrollment_dropouts_inst_2022 = pd.merge(sctevt_enrollment_inst_2022, sctevt_dropouts_inst_2022, on="institute_name", how="left")
sctevt_enrollment_dropouts_inst_2022["dropout_rate"] = sctevt_enrollment_dropouts_inst_2022["dropouts"].div(sctevt_enrollment_dropouts_inst_2022["enrollment"]).mul(100).round(1)
sctevt_enrollment_dropouts_inst_2022 = sctevt_enrollment_dropouts_inst_2022.sort_values(by="enrollment", ascending=False)
sctevt_enrollment_dropouts_inst_2022

In [ ]:
# Dropouts by trade and gender, public
sctevt_dropouts_trade_gender_public = pd.pivot_table(
    sctevt_df[sctevt_df["type_of_institute"] == "Govt."],
    index="trade",
    columns="gender",
    values="roll_num",
    aggfunc="nunique"
)

sctevt_dropouts_trade_gender_public = sctevt_dropouts_trade_gender_public.astype("Int64")
sctevt_dropouts_trade_gender_public["Total"] = sctevt_dropouts_trade_gender_public.sum(axis=1)
sctevt_dropouts_trade_gender_public.sort_values(by="Total", ascending=False, inplace=True)

In [ ]:
sctevt_dropouts_trade_gender_private = pd.pivot_table(
    sctevt_df[sctevt_df["type_of_institute"] == "Pvt."],
    index="trade",
    columns="gender",
    values="roll_num",
    aggfunc="nunique"
)

sctevt_dropouts_trade_gender_private = sctevt_dropouts_trade_gender_private.astype("Int64")
sctevt_dropouts_trade_gender_private = sctevt_dropouts_trade_gender_private.drop(columns=["O"])
sctevt_dropouts_trade_gender_private = sctevt_dropouts_trade_gender_private.fillna(0)
sctevt_dropouts_trade_gender_private["Total"] = sctevt_dropouts_trade_gender_private.sum(axis=1)
sctevt_dropouts_trade_gender_private.sort_values(by="Total", ascending=False, inplace=True)

In [ ]:
sctevt_dropouts_trade_gender_private

gender                                              Female   Male  Total
trade
Electrician (NSQF)                                    6909  79658  86567
Fitter (NSQF)                                         4245  77222  81467
Computer Operator and Programming Assistant (NSQF)    1181   1285   2466
Welder (NSQF)                                           86   1869   1955
Sewing Technology (NSQF)                              1651    106   1757
Mechanic (Motor Vehicle) (NSQF)                          9   1101   1110
Electronics Mechanic (NSQF)                            272    586    858
Plumber (NSQF)                                          56    512    568
Mechanic Diesel (NSQF)                                  18    483    501
Machinist (NSQF)                                        10    464    474
Stenographer & Secretarial Assistant (English) ...      91     31    122
Wireman (NSQF)                                          10     70     80
Health Sanitary Inspector (NSQF)                        46     26     72
Surveyor (NSQF)                                         31     35     66
Horticulture (NSQF)                                     39     25     64
REFRIGERATION AND AIR CONDITIONING TECHNICIAN(N...       3     61     64
Desk Top Publishing Operator (NSQF)                     34     18     52
Mechanic (Refrigeration and Air-Conditioning) (...       0     48     48
Mason (Building Constructor) (NSQF)                      5     39     44
Information Communication Technology System Mai...       3     38     41
Turner (NSQF)                                            2     38     40
Secretarial Practice (English) (NSQF)                   33      5     38
Cosmetology (NSQF)                                      31      0     31
Mechanic Motor Cycle (NSQF)                              0     19     19
Carpenter (NSQF)                                         0      4      4
Photographer (NSQF)                                      0      4      4
Draughtsman (Civil) (NSQF)                               0      1      1
Basic Cosmetology (NSQF)                                 1      0      1

In [31]:
from sams.config import OUTPUT_DIR
dfs = [
    sctevt_enrollment_trades_gender_2022,
    sctevt_dropouts_trades_gender_2022,
    sctevt_dropouts_trade_gender_public,
    sctevt_dropouts_trade_gender_private,
]
sheet_names = [
    "SCTEVT Enrollments by Trade and Gender (2022)",
    "SCTEVT Dropouts by Trade and Gender (2022)",
    "SCTEVT Dropouts by Trade and Gender (Public)",
    "SCTEVT Dropouts by Trade and Gender (Private)"
]
index = [True, True, True, True]
save_table_excel(dfs, sheet_names, index, outfile= OUTPUT_DIR / "sctevt_dropouts_trade_gender_institute.xlsx")

2025-07-08 11:49:08.017 | INFO     | sams.analysis.utils:save_table_excel:123 - Saving DataFrame to sheet: SCTEVT Enrollments by Trade and Gender (2022) to /Users/ymohanty/Documents/GitHub/sams/output/sctevt_dropouts_trade_gender_institute.xlsx
2025-07-08 11:49:08.022 | INFO     | sams.analysis.utils:save_table_excel:123 - Saving DataFrame to sheet: SCTEVT Dropouts by Trade and Gender (2022) to /Users/ymohanty/Documents/GitHub/sams/output/sctevt_dropouts_trade_gender_institute.xlsx
2025-07-08 11:49:08.030 | INFO     | sams.analysis.utils:save_table_excel:123 - Saving DataFrame to sheet: SCTEVT Dropouts by Trade and Gender (Public) to /Users/ymohanty/Documents/GitHub/sams/output/sctevt_dropouts_trade_gender_institute.xlsx
2025-07-08 11:49:08.037 | INFO     | sams.analysis.utils:save_table_excel:123 - Saving DataFrame to sheet: SCTEVT Dropouts by Trade and Gender (Private) to /Users/ymohanty/Documents/GitHub/sams/output/sctevt_dropouts_trade_gender_institute.xlsx

/opt/anaconda3/envs/skills/lib/python3.10/site-packages/openpyxl/workbook/child.py:99: UserWarning: Title is more than 31 characters. Some applications may not be able to read the file
  warnings.warn("Title is more than 31 characters. Some applications may not be able to read the file")